# Projeto3 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projeto3
  template:
    metadata:
      labels:
        app: projeto3
    spec:
      containers:
      - name: projeto3
        image: andrrade/meu-backend:16  # Substituí pela imagem válida
        ports:
        - containerPort: 8080
---
# Projeto3 Service
apiVersion: v1
kind: Service
metadata:
  name: projeto3
spec:
  selector:
    app: projeto3
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: andrrade/meu-frontend:13  # Corrigido com a tag correta
        ports:
        - containerPort: 3000
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: andrrade/meu-backend:16  # Corrigido com a tag correta
        ports:
        - containerPort: 8000
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30001
  type: NodePort
