# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: default
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: andrrade/meu-frontend:v1.0.0
          imagePullPolicy: Always  # Mudado para Always para garantir que pegue a versão mais recente
          ports:
            - containerPort: 3000
              name: http
          # Health checks - Temporariamente desabilitado para debug
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 3
          # Recursos
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          # Variáveis de ambiente
          env:
            - name: NODE_ENV
              value: "production"

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
  type: NodePort

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: andrrade/meu-backend:v1.0.0
          imagePullPolicy: Always  # Mudado para Always
          ports:
            - containerPort: 8000
              name: http
          # Health checks - Temporariamente desabilitado para debug
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 3
          # Recursos
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Variáveis de ambiente
          env:
            - name: PYTHONPATH
              value: "/app"

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30001  # Corrigido para 30001 em vez de 30081
      protocol: TCP
  type: NodePort
  